

variables:
  DOCKER_TLS_CERTDIR: ""
  INSECURE_REGISTRY: "--insecure-registry=$CI_REGISTRY"

stages:
  - build-unit-tests
  - build-integration-tests
  - coverage-report
  - package

test-junit:
  image: maven:3.6-openjdk-11-slim
  stage: build-unit-tests
  script: "mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install -Dtest=PromotionTest,ProductTest,PropertyTest,MapperProductServiceTests jacoco:report"
  artifacts:
    paths:
      - target/*.jar
      - target/site/jacoco/jacoco.xml
  tags:
    - kubernetes

test-integration:
  image: maven:3.6-openjdk-11-slim
  stage: build-integration-tests
  services:
    - name: docker:18.09.7-dind
  only:
    - master
    - tags
  script: "mvn clean install -Dtest=CatalogDockerTest"
  artifacts:
    paths:
      - target/*.jar
  tags:
    - kubernetes

docker-build:
  tags:
    - kubernetes
  image: docker:18.09.7
  stage: package
  services:
    - name: docker:18.09.7-dind
      command: [ "--insecure-registry=registry.gitlab.local.com:5050" ]
  before_script:
    - echo $INSECURE_REGISTRY
    - echo "$INSECURE_REGISTRY"
    - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY/$DOCKER_PROJECT_PATH:$DOCKER_TAG .
    - docker push $CI_REGISTRY/$DOCKER_PROJECT_PATH:$DOCKER_TAG

coverage-report:
  # Must be in a stage later than test-jdk11's stage.
  # The `visualize` stage does not exist by default.
  # Please define it first, or chose an existing stage like `deploy`.
  stage: coverage-report
  image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.7
  tags:
    - kubernetes
  script:
    # convert report from jacoco to cobertura
    - 'python /opt/cover2cover.py target/site/jacoco/jacoco.xml src/main/java > target/site/cobertura.xml'
    # read the <source></source> tag and prepend the path to every filename attribute
    - 'python /opt/source2filename.py target/site/cobertura.xml'
  needs: ["test-junit"]
  dependencies:
    - test-junit
  artifacts:
    reports:
      cobertura: target/site/cobertura.xml

